spring.application.name=card-management-service
server.port=8082

spring.datasource.url=jdbc:h2:file:./data/card-management;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
